services:
  miniflux:
    image: miniflux/miniflux:latest
    container_name: miniflux
    ports:
      - "80:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://miniflux:secret@db/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - DISABLE_HSTS=1
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=test123
    healthcheck:
      test: ["CMD", "/usr/bin/miniflux", "-healthcheck", "auto"]
    restart: unless-stopped
  db:
    image: postgres:17-alpine
    container_name: miniflux-db
    environment:
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=miniflux
    volumes:
      - miniflux-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 10s
    restart: unless-stopped
  nextflux:
    image: electh/nextflux:latest
    container_name: nextflux
    ports:
      - 3000:3000
    depends_on:
      miniflux:
        condition: service_healthy
    restart: unless-stopped
volumes:
  miniflux-db:
